source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.4.1"

# minimal mistakes theme, https://mmistakes.github.io/minimal-mistakes/
gem "minimal-mistakes-jekyll", "~> 4.27.3"

group :jekyll_plugins do
    gem "jekyll-spaceship", "~> 0.10.2"
    gem "jekyll-feed", "~> 0.17.0"
end
